/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple;

import common.FileChooser;
import common.FileOperate;
import java.io.File;
import java.io.IOException;
import static java.lang.Math.abs;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class CompareTool extends javax.swing.JFrame {

    private File file1;
    private File file2;
    double[][] data1;
    double[][] data2;

    /**
     * Creates new form CompareTool
     */
    public CompareTool(Object o) {
        if (o == null) {
            initComponents();
            this.setVisible(true);
            this.setTitle("文本对比工具");
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        contentTabbedPane = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("打开文件1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        contentTabbedPane.setToolTipText("对比结果");
        contentTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contentTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                contentTabbedPaneStateChanged(evt);
            }
        });

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        contentTabbedPane.addTab("对比结果", jTabbedPane1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setSelectionEnd(1);
        jTextArea2.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTextArea2);
        jTextArea2.getAccessibleContext().setAccessibleName("输入数据");
        jTextArea2.getAccessibleContext().setAccessibleDescription("");

        jSplitPane1.setRightComponent(jScrollPane2);

        contentTabbedPane.addTab("输入文本", jSplitPane1);

        contentTabbedPane.setSelectedComponent(jSplitPane1);

        jButton2.setText("打开文件2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("对比数据");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(contentTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(contentTabbedPane)
                .addGap(27, 27, 27))
        );

        contentTabbedPane.getAccessibleContext().setAccessibleName("输入数据");
        contentTabbedPane.getAccessibleContext().setAccessibleDescription("结果");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        file1 = new FileChooser("打开", 1).getFile();
        FileOperate fileOperate = new FileOperate(file1);
        data1 = fileOperate.readFromFileDoubleArray2(file1);
        String[] lines = fileOperate.readFromFileStringArray(file1);
        jTextArea1.setText("");
        try {
            jTextArea1.setToolTipText(file1.getCanonicalPath());
        } catch (IOException ex) {
            Logger.getLogger(CompareTool.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < lines.length; i++) {
            jTextArea1.append(lines[i]);
            jTextArea1.append("\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        file2 = new FileChooser("打开", 1).getFile();
        FileOperate fileOperate = new FileOperate(file2);
        data2 = fileOperate.readFromFileDoubleArray2(file2);
        String[] lines = fileOperate.readFromFileStringArray(file1);
        jTextArea2.setText("");

        try {
            jTextArea2.setToolTipText(file2.getCanonicalPath());
        } catch (IOException ex) {
            Logger.getLogger(CompareTool.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < lines.length; i++) {
            jTextArea2.append(lines[i]);
            jTextArea2.append("\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.out.println(delta(data1, data2));
        jTextArea3.setText("");
        for (int i = 0; i < data1.length; i++) {
            for (int j = 0; j < data1[0].length; j++) {

                String line = i + "    " + j + "    " + Double.toString(data1[i][j]);
                line = line + "    " + Double.toString(data2[i][j]);
                line = line + "    " + Double.toString((data1[i][j] - data2[i][j])) + "\n";
                jTextArea3.append(line);
            }
        }
        contentTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void contentTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_contentTabbedPaneStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_contentTabbedPaneStateChanged

    private void displayData(File file) {

    }

    private double delta(double[] f, double[] fLast) {
        double delta = 0;
        for (int i = 0; i < f.length; i++) {
            if (abs(f[i] - fLast[i]) > delta) {
                delta = abs(f[i] - fLast[i]);
            }
        }
        return delta;
    }

    private double delta(double[][] f, double[][] fLast) {
        double delta = 0;
        for (int i = 0; i < f.length; i++) {
            for (int j = 0; j < f[0].length; j++) {
                if (abs(f[i][j] - fLast[i][j]) > delta) {
                    delta = abs(f[i][j] - fLast[i][j]);
                }
            }
        }
        return delta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane contentTabbedPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
